runtime: nodejs18
service: default

handlers:
    - url: /static/js/(.*)
      static_files: dist/assets/\1
      upload: dist/assets/(.*)
      secure: always

    - url: /(.*\.(json|ico|png|jpg|svg|js))$
      static_files: dist/\1
      upload: dist/.*\.(json|ico|png|jpg|svg|js)$
      secure: always

    - url: /mockServiceWorker.js
      static_files: dist/mockServiceWorker.js
      upload: dist/mockServiceWorker.js
      secure: always

    - url: /
      static_files: dist/index.html
      upload: dist/index.html
      secure: always

    - url: /.*
      static_files: dist/index.html
      upload: dist/index.html
      secure: always
