export const category = [
    {
        categoryLabel: "상의",
        categoryValue: "TOPS",
        subCategory: [
            { categoryLabel: "반소매 티셔츠", categoryValue: "SHORT_SLEEVE_TSHIRT" },
            { categoryLabel: "긴팔 티셔츠", categoryValue: "LONG_SLEEVE_TSHIRT" },
            { categoryLabel: "민소매", categoryValue: "SLEEVELESS" },
            { categoryLabel: "카라티", categoryValue: "POLO_SHIRT" },
            { categoryLabel: "탱크탑", categoryValue: "TANK_TOP" },
            { categoryLabel: "크롭탑", categoryValue: "CROP_TOP" },
            { categoryLabel: "블라우스", categoryValue: "BLOUSE" },
            { categoryLabel: "긴팔셔츠", categoryValue: "LONG_SLEEVE_SHIRT" },
            { categoryLabel: "반팔셔츠", categoryValue: "SHORT_SLEEVE_SHIRT" },
            { categoryLabel: "맨투맨", categoryValue: "CREW_NECK_SWEATER" },
            { categoryLabel: "후드", categoryValue: "HOODIE" },
            { categoryLabel: "니트", categoryValue: "KNITWEAR" },
            { categoryLabel: "니트조끼", categoryValue: "KNIT_VEST" },
            { categoryLabel: "스포츠상의", categoryValue: "SPORTS_TOP" },
            { categoryLabel: "바디수트", categoryValue: "BODYSUIT" },
        ],
    },
    {
        categoryLabel: "원피스",
        categoryValue: "DRESSES",
        subCategory: [
            { categoryLabel: "캐주얼 원피스", categoryValue: "CASUAL_DRESS" },
            { categoryLabel: "티셔츠 원피스", categoryValue: "TSHIRT_DRESS" },
            { categoryLabel: "셔츠 원피스", categoryValue: "SHIRT_DRESS" },
            { categoryLabel: "후드 원피스", categoryValue: "HOODED_DRESS" },
            { categoryLabel: "니트 원피스", categoryValue: "KNIT_DRESS" },
            { categoryLabel: "자켓 원피스", categoryValue: "JACKET_DRESS" },
            { categoryLabel: "멜빵 원피스", categoryValue: "DUNGAREE_DRESS" },
            { categoryLabel: "점프수트", categoryValue: "JUMPSUIT" },
            { categoryLabel: "이브닝 원피스", categoryValue: "EVENING_DRESS" },
            { categoryLabel: "미니 원피스", categoryValue: "MINI_DRESS" },
        ],
    },
    {
        categoryLabel: "바지",
        categoryValue: "PANTS",
        subCategory: [
            { categoryLabel: "청바지", categoryValue: "JEANS" },
            { categoryLabel: "긴바지", categoryValue: "LONG_PANTS" },
            { categoryLabel: "정장바지", categoryValue: "DRESS_PANTS" },
            { categoryLabel: "운동복", categoryValue: "ATHLETIC_PANTS" },
            { categoryLabel: "레깅스", categoryValue: "LEGGINGS" },
            { categoryLabel: "반바지", categoryValue: "SHORTS" },
        ],
    },
    {
        categoryLabel: "치마",
        categoryValue: "SKIRTS",
        subCategory: [
            { categoryLabel: "미니스커트", categoryValue: "MINI_SKIRT" },
            { categoryLabel: "미디스커트", categoryValue: "MIDI_SKIRT" },
            { categoryLabel: "롱스커트", categoryValue: "LONG_SKIRT" },
        ],
    },
    {
        categoryLabel: "아우터",
        categoryValue: "OUTERWEAR",
        subCategory: [
            { categoryLabel: "코트", categoryValue: "COAT" },
            { categoryLabel: "트렌치", categoryValue: "TRENCH_COAT" },
            { categoryLabel: "털코트", categoryValue: "FUR_COAT" },
            { categoryLabel: "무스탕", categoryValue: "MOUTON_COAT" },
            { categoryLabel: "블레이저", categoryValue: "BLAZER" },
            { categoryLabel: "자켓", categoryValue: "JACKET" },
            { categoryLabel: "블루종", categoryValue: "BOMBER_JACKET" },
            { categoryLabel: "야구잠바", categoryValue: "BASEBALL_JACKET" },
            { categoryLabel: "트러커", categoryValue: "TRUCKER_JACKET" },
            { categoryLabel: "라이더자켓", categoryValue: "RIDER_JACKET" },
            { categoryLabel: "가디건", categoryValue: "CARDIGAN" },
            { categoryLabel: "집업", categoryValue: "ZIP_UP_JACKET" },
            { categoryLabel: "야상", categoryValue: "MILITARY_JACKET" },
            { categoryLabel: "스포츠아우터", categoryValue: "SPORTS_OUTERWEAR" },
            { categoryLabel: "후리스", categoryValue: "FLEECE" },
            { categoryLabel: "파카", categoryValue: "PARKA" },
            { categoryLabel: "경량패딩", categoryValue: "LIGHTWEIGHT_PADDED_JACKET" },
            { categoryLabel: "패딩", categoryValue: "PADDED_JACKET" },
            { categoryLabel: "조끼", categoryValue: "VEST" },
        ],
    },
    {
        categoryLabel: "모자",
        categoryValue: "HATS",
        subCategory: [
            { categoryLabel: "캡", categoryValue: "CAP" },
            { categoryLabel: "햇", categoryValue: "HAT" },
            { categoryLabel: "비니", categoryValue: "BEANIE" },
            { categoryLabel: "베레모", categoryValue: "BERET" },
            { categoryLabel: "페도라", categoryValue: "FEDORA" },
            { categoryLabel: "썬햇", categoryValue: "SUN_HAT" },
        ],
    },
    {
        categoryLabel: "신발",
        categoryValue: "SHOES",
        subCategory: [
            { categoryLabel: "스니커즈", categoryValue: "SNEAKERS" },
            { categoryLabel: "슬립온", categoryValue: "SLIP_ON" },
            { categoryLabel: "운동화", categoryValue: "ATHLETIC_SHOES" },
            { categoryLabel: "등산화", categoryValue: "HIKING_BOOTS" },
            { categoryLabel: "부츠", categoryValue: "BOOTS" },
            { categoryLabel: "워커", categoryValue: "WORKER_BOOTS" },
            { categoryLabel: "어그부츠", categoryValue: "UGG_BOOTS" },
            { categoryLabel: "로퍼", categoryValue: "LOAFERS" },
            { categoryLabel: "보트", categoryValue: "BOAT_SHOES" },
            { categoryLabel: "플랫슈즈", categoryValue: "FLATS" },
            { categoryLabel: "힐", categoryValue: "HEELS" },
            { categoryLabel: "샌들", categoryValue: "SANDALS" },
            { categoryLabel: "샌들힐", categoryValue: "SANDAL_HEELS" },
            { categoryLabel: "슬리퍼", categoryValue: "SLIPPERS" },
            { categoryLabel: "뮬힐", categoryValue: "MULE_HEELS" },
        ],
    },
    {
        categoryLabel: "가방",
        categoryValue: "BAGS",
        subCategory: [
            { categoryLabel: "토트백", categoryValue: "TOTE_BAG" },
            { categoryLabel: "숄더백", categoryValue: "SHOULDER_BAG" },
            { categoryLabel: "크로스백", categoryValue: "CROSSBODY_BAG" },
            { categoryLabel: "웨이스트백", categoryValue: "WAIST_BAG" },
            { categoryLabel: "에코백", categoryValue: "ECO_BAG" },
            { categoryLabel: "백팩", categoryValue: "BACKPACK" },
            { categoryLabel: "보스턴백", categoryValue: "BOSTON_BAG" },
            { categoryLabel: "클러치백", categoryValue: "CLUTCH_BAG" },
            { categoryLabel: "서류가방", categoryValue: "DOCUMENT_BAG" },
            { categoryLabel: "짐색", categoryValue: "DUFFLE_BAG" },
            { categoryLabel: "캐리어", categoryValue: "LUGGAGE" },
        ],
    },
];
