export const category = [
    {
        categoryLabel: "상의",
        categoryValue: "상의",
        subCategory: [
            { categoryLabel: "반소매 티셔츠", categoryValue: "반소매 티셔츠" },
            { categoryLabel: "긴팔 티셔츠", categoryValue: "긴팔 티셔츠" },
            { categoryLabel: "민소매", categoryValue: "민소매" },
            { categoryLabel: "카라티", categoryValue: "P카라티" },
            { categoryLabel: "탱크탑", categoryValue: "탱크탑" },
            { categoryLabel: "크롭탑", categoryValue: "크롭탑" },
            { categoryLabel: "블라우스", categoryValue: "블라우스" },
            { categoryLabel: "긴팔셔츠", categoryValue: "긴팔셔츠" },
            { categoryLabel: "반팔셔츠", categoryValue: "반팔셔츠" },
            { categoryLabel: "맨투맨", categoryValue: "맨투맨" },
            { categoryLabel: "후드", categoryValue: "후드" },
            { categoryLabel: "니트", categoryValue: "니트" },
            { categoryLabel: "니트조끼", categoryValue: "니트조끼" },
            { categoryLabel: "스포츠상의", categoryValue: "스포츠상의" },
            { categoryLabel: "바디수트", categoryValue: "바디수트" },
        ],
    },
    {
        categoryLabel: "원피스",
        categoryValue: "원피스",
        subCategory: [
            { categoryLabel: "캐주얼 원피스", categoryValue: "캐주얼 원피스" },
            { categoryLabel: "티셔츠 원피스", categoryValue: "티셔츠 원피스" },
            { categoryLabel: "셔츠 원피스", categoryValue: "셔츠 원피스" },
            { categoryLabel: "후드 원피스", categoryValue: "후드 원피스" },
            { categoryLabel: "니트 원피스", categoryValue: "니트 원피스" },
            { categoryLabel: "자켓 원피스", categoryValue: "자켓 원피스" },
            { categoryLabel: "멜빵 원피스", categoryValue: "멜빵 원피스" },
            { categoryLabel: "점프수트", categoryValue: "점프수트" },
            { categoryLabel: "이브닝 원피스", categoryValue: "이브닝 원피스" },
            { categoryLabel: "미니 원피스", categoryValue: "미니 원피스" },
        ],
    },
    {
        categoryLabel: "바지",
        categoryValue: "바지",
        subCategory: [
            { categoryLabel: "청바지", categoryValue: "청바지" },
            { categoryLabel: "긴바지", categoryValue: "긴바지" },
            { categoryLabel: "정장바지", categoryValue: "정장바지" },
            { categoryLabel: "운동복", categoryValue: "운동복" },
            { categoryLabel: "레깅스", categoryValue: "레깅스" },
            { categoryLabel: "반바지", categoryValue: "반바지" },
        ],
    },
    {
        categoryLabel: "치마",
        categoryValue: "치마",
        subCategory: [
            { categoryLabel: "미니스커트", categoryValue: "미니스커트" },
            { categoryLabel: "미디스커트", categoryValue: "미디스커트" },
            { categoryLabel: "롱스커트", categoryValue: "롱스커트" },
        ],
    },
    {
        categoryLabel: "아우터",
        categoryValue: "아우터",
        subCategory: [
            { categoryLabel: "코트", categoryValue: "코트" },
            { categoryLabel: "트렌치", categoryValue: "트렌치" },
            { categoryLabel: "털코트", categoryValue: "털코트" },
            { categoryLabel: "무스탕", categoryValue: "무스탕" },
            { categoryLabel: "블레이저", categoryValue: "블레이저" },
            { categoryLabel: "자켓", categoryValue: "자켓" },
            { categoryLabel: "블루종", categoryValue: "블루종" },
            { categoryLabel: "야구잠바", categoryValue: "야구잠바" },
            { categoryLabel: "트러커", categoryValue: "트러커" },
            { categoryLabel: "라이더자켓", categoryValue: "라이더자켓" },
            { categoryLabel: "가디건", categoryValue: "가디건" },
            { categoryLabel: "집업", categoryValue: "집업" },
            { categoryLabel: "야상", categoryValue: "야상" },
            { categoryLabel: "스포츠아우터", categoryValue: "스포츠아우터" },
            { categoryLabel: "후리스", categoryValue: "후리스" },
            { categoryLabel: "파카", categoryValue: "파카" },
            { categoryLabel: "경량패딩", categoryValue: "경량패딩" },
            { categoryLabel: "패딩", categoryValue: "패딩" },
            { categoryLabel: "조끼", categoryValue: "조끼" },
        ],
    },
    {
        categoryLabel: "모자",
        categoryValue: "모자",
        subCategory: [
            { categoryLabel: "캡", categoryValue: "캡" },
            { categoryLabel: "햇", categoryValue: "햇" },
            { categoryLabel: "비니", categoryValue: "비니" },
            { categoryLabel: "베레모", categoryValue: "베레모" },
            { categoryLabel: "페도라", categoryValue: "페도라" },
            { categoryLabel: "썬햇", categoryValue: "썬햇" },
        ],
    },
    {
        categoryLabel: "신발",
        categoryValue: "신발",
        subCategory: [
            { categoryLabel: "스니커즈", categoryValue: "스니커즈" },
            { categoryLabel: "슬립온", categoryValue: "슬립온" },
            { categoryLabel: "운동화", categoryValue: "운동화" },
            { categoryLabel: "등산화", categoryValue: "등산화" },
            { categoryLabel: "부츠", categoryValue: "부츠" },
            { categoryLabel: "워커", categoryValue: "워커" },
            { categoryLabel: "어그부츠", categoryValue: "어그부츠" },
            { categoryLabel: "로퍼", categoryValue: "로퍼" },
            { categoryLabel: "보트", categoryValue: "보트" },
            { categoryLabel: "플랫슈즈", categoryValue: "플랫슈즈" },
            { categoryLabel: "힐", categoryValue: "힐" },
            { categoryLabel: "샌들", categoryValue: "샌들" },
            { categoryLabel: "샌들힐", categoryValue: "샌들힐" },
            { categoryLabel: "슬리퍼", categoryValue: "슬리퍼" },
            { categoryLabel: "뮬힐", categoryValue: "뮬힐" },
        ],
    },
    {
        categoryLabel: "가방",
        categoryValue: "가방",
        subCategory: [
            { categoryLabel: "토트백", categoryValue: "토트백" },
            { categoryLabel: "숄더백", categoryValue: "숄더백" },
            { categoryLabel: "크로스백", categoryValue: "크로스백" },
            { categoryLabel: "웨이스트백", categoryValue: "웨이스트백" },
            { categoryLabel: "에코백", categoryValue: "에코백" },
            { categoryLabel: "백팩", categoryValue: "백팩" },
            { categoryLabel: "보스턴백", categoryValue: "보스턴백" },
            { categoryLabel: "클러치백", categoryValue: "클러치백" },
            { categoryLabel: "서류가방", categoryValue: "서류가방" },
            { categoryLabel: "짐색", categoryValue: "짐색" },
            { categoryLabel: "캐리어", categoryValue: "캐리어" },
        ],
    },
];
